package com.mfund.model;

import java.util.List;

/**
 * Response model for the AI Fund Analyst feature.
 *
 * Contains both quantitative data fetched from real APIs (beta, 1-year return)
 * and qualitative analysis generated by the LLM using those real numbers as context.
 */
public class FundAnalysis {

    private String ticker;
    private String fundName;

    /** Beta vs. S&P 500 fetched live from Newton Analytics. */
    private double beta;

    /** 1-year historical return fetched live from Yahoo Finance. */
    private double oneYearReturn;

    /** LLM: 2-3 sentence description of this fund's investment strategy and mandate. */
    private String strategyOverview;

    /** LLM: risk assessment grounded in the actual beta value. */
    private String riskAssessment;

    /** LLM: description of which investor profile this fund best suits. */
    private String investorProfile;

    /** LLM: 3 specific things to know before investing in this fund. */
    private List<String> keyConsiderations;

    /** LLM: brief concluding recommendation. */
    private String summary;

    public FundAnalysis() {}

    // ── Getters & Setters ──────────────────────────────────────────────────────

    public String getTicker() { return ticker; }
    public String getFundName() { return fundName; }
    public double getBeta() { return beta; }
    public double getOneYearReturn() { return oneYearReturn; }
    public String getStrategyOverview() { return strategyOverview; }
    public String getRiskAssessment() { return riskAssessment; }
    public String getInvestorProfile() { return investorProfile; }
    public List<String> getKeyConsiderations() { return keyConsiderations; }
    public String getSummary() { return summary; }

    public void setTicker(String ticker) { this.ticker = ticker; }
    public void setFundName(String fundName) { this.fundName = fundName; }
    public void setBeta(double beta) { this.beta = beta; }
    public void setOneYearReturn(double oneYearReturn) { this.oneYearReturn = oneYearReturn; }
    public void setStrategyOverview(String strategyOverview) { this.strategyOverview = strategyOverview; }
    public void setRiskAssessment(String riskAssessment) { this.riskAssessment = riskAssessment; }
    public void setInvestorProfile(String investorProfile) { this.investorProfile = investorProfile; }
    public void setKeyConsiderations(List<String> keyConsiderations) { this.keyConsiderations = keyConsiderations; }
    public void setSummary(String summary) { this.summary = summary; }
}
